name                 = "subsuku"                    # Workers サブドメイン名
main                 = ".open-next/worker.js"       # OpenNext が出力するエントリ
compatibility_date   = "2025-05-04"                 # 互換性の基準日
compatibility_flags  = ["nodejs_compat"]            # Node.js API 互換モード

# 静的アセット設定
[assets]
directory = ".open-next/assets"  # 静的アセット配置ディレクトリ
binding   = "ASSETS"             # バインディング名

# ログ設定
[observability.logs]
enabled = true
